import { Geist, Geist_Mono } from "next/font/google";
import { Arimo, Nunito } from "next/font/google";
import "./globals.css";
import Menu from "@components/Menu"; // Import Menu Component
import Footer from './../components/Footer';


const arimo = Arimo({ subsets: ["latin"], weight: ["400", "600", "700"], variable: "--font-arimo" });
const nunito = Nunito({ subsets: ["latin"], weight: ["400", "600", "700"], variable: "--font-nunito" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Menu /> 
      {/* Navbar */}
      <main className="container mx-auto ">{children}</main>
      <Footer/>
      </body>
    </html>
  );
}
